/**
 * AUTO-GENERATED by `npm run validate-content`. Do not edit by hand.
 * Small numeric summary of content volume, kept eager (tiny) so Settings/Progress/
 * level-select tiles can show real counts without lazy-loading full content banks.
 */
export interface ContentStats {
  generatedAt: string;
  grammar: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  vocabulary: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  readingMaterials: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  readingQuestions: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  writing: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  grammarTheory: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  grammarTerms: { total: number };
  toeic: { total: number; byPart: Record<1 | 2 | 3 | 4 | 5 | 6 | 7, number> };
}

export const CONTENT_STATS: ContentStats = {
  "generatedAt": "2026-09-10T00:27:14.074Z",
  "grammar": {
    "total": 800,
    "byLevel": {
      "1": 200,
      "2": 200,
      "3": 150,
      "4": 100,
      "5": 100,
      "6": 50
    }
  },
  "vocabulary": {
    "total": 2500,
    "byLevel": {
      "1": 452,
      "2": 503,
      "3": 500,
      "4": 391,
      "5": 284,
      "6": 370
    }
  },
  "readingMaterials": {
    "total": 160,
    "byLevel": {
      "1": 30,
      "2": 30,
      "3": 30,
      "4": 20,
      "5": 30,
      "6": 20
    }
  },
  "readingQuestions": {
    "total": 953,
    "byLevel": {
      "1": 150,
      "2": 150,
      "3": 213,
      "4": 142,
      "5": 178,
      "6": 120
    }
  },
  "writing": {
    "total": 200,
    "byLevel": {
      "1": 45,
      "2": 37,
      "3": 30,
      "4": 28,
      "5": 29,
      "6": 31
    }
  },
  "grammarTheory": {
    "total": 110,
    "byLevel": {
      "1": 28,
      "2": 34,
      "3": 22,
      "4": 13,
      "5": 13,
      "6": 0
    }
  },
  "grammarTerms": {
    "total": 103
  },
  "toeic": {
    "total": 300,
    "byPart": {
      "1": 20,
      "2": 40,
      "3": 13,
      "4": 11,
      "5": 185,
      "6": 13,
      "7": 18
    }
  }
};
