/**
 * AUTO-GENERATED by `npm run validate-content`. Do not edit by hand.
 * Small numeric summary of content volume, kept eager (tiny) so Settings/Progress/
 * level-select tiles can show real counts without lazy-loading full content banks.
 */
export interface ContentStats {
  generatedAt: string;
  grammar: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  vocabulary: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  readingMaterials: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  readingQuestions: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  writing: { total: number; byLevel: Record<1 | 2 | 3 | 4 | 5 | 6, number> };
  toeic: { total: number; byPart: Record<1 | 2 | 3 | 4 | 5 | 6 | 7, number> };
}

export const CONTENT_STATS: ContentStats = {
  "generatedAt": "2026-09-07T03:12:24.996Z",
  "grammar": {
    "total": 570,
    "byLevel": {
      "1": 192,
      "2": 132,
      "3": 92,
      "4": 59,
      "5": 55,
      "6": 40
    }
  },
  "vocabulary": {
    "total": 575,
    "byLevel": {
      "1": 200,
      "2": 120,
      "3": 80,
      "4": 70,
      "5": 45,
      "6": 60
    }
  },
  "readingMaterials": {
    "total": 33,
    "byLevel": {
      "1": 6,
      "2": 5,
      "3": 5,
      "4": 5,
      "5": 7,
      "6": 5
    }
  },
  "readingQuestions": {
    "total": 94,
    "byLevel": {
      "1": 12,
      "2": 10,
      "3": 20,
      "4": 19,
      "5": 18,
      "6": 15
    }
  },
  "writing": {
    "total": 99,
    "byLevel": {
      "1": 28,
      "2": 20,
      "3": 13,
      "4": 11,
      "5": 12,
      "6": 15
    }
  },
  "toeic": {
    "total": 102,
    "byPart": {
      "1": 10,
      "2": 25,
      "3": 5,
      "4": 4,
      "5": 45,
      "6": 5,
      "7": 8
    }
  }
};
